// Generated by purs bundle 0.13.2
var PS = {};
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Control.Applicative"] = $PS["Control.Applicative"] || {};
  var exports = $PS["Control.Applicative"];        
  var Applicative = function (Apply0, pure) {
      this.Apply0 = Apply0;
      this.pure = pure;
  };
  var pure = function (dict) {
      return dict.pure;
  };
  exports["Applicative"] = Applicative;
  exports["pure"] = pure;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Control.Apply"] = $PS["Control.Apply"] || {};
  var exports = $PS["Control.Apply"];                    
  var Apply = function (Functor0, apply) {
      this.Functor0 = Functor0;
      this.apply = apply;
  };                      
  var apply = function (dict) {
      return dict.apply;
  };
  exports["Apply"] = Apply;
  exports["apply"] = apply;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Control.Bind"] = $PS["Control.Bind"] || {};
  var exports = $PS["Control.Bind"];
  var Bind = function (Apply0, bind) {
      this.Apply0 = Apply0;
      this.bind = bind;
  };                     
  var bind = function (dict) {
      return dict.bind;
  };
  exports["Bind"] = Bind;
  exports["bind"] = bind;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Control.Semigroupoid"] = $PS["Control.Semigroupoid"] || {};
  var exports = $PS["Control.Semigroupoid"];
  var Semigroupoid = function (compose) {
      this.compose = compose;
  };
  var semigroupoidFn = new Semigroupoid(function (f) {
      return function (g) {
          return function (x) {
              return f(g(x));
          };
      };
  });
  var compose = function (dict) {
      return dict.compose;
  };
  exports["compose"] = compose;
  exports["Semigroupoid"] = Semigroupoid;
  exports["semigroupoidFn"] = semigroupoidFn;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Control.Category"] = $PS["Control.Category"] || {};
  var exports = $PS["Control.Category"];
  var Control_Semigroupoid = $PS["Control.Semigroupoid"];                
  var Category = function (Semigroupoid0, identity) {
      this.Semigroupoid0 = Semigroupoid0;
      this.identity = identity;
  };
  var identity = function (dict) {
      return dict.identity;
  };
  var categoryFn = new Category(function () {
      return Control_Semigroupoid.semigroupoidFn;
  }, function (x) {
      return x;
  });
  exports["Category"] = Category;
  exports["identity"] = identity;
  exports["categoryFn"] = categoryFn;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Control.Monad"] = $PS["Control.Monad"] || {};
  var exports = $PS["Control.Monad"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];                
  var Monad = function (Applicative0, Bind1) {
      this.Applicative0 = Applicative0;
      this.Bind1 = Bind1;
  };
  var ap = function (dictMonad) {
      return function (f) {
          return function (a) {
              return Control_Bind.bind(dictMonad.Bind1())(f)(function (v) {
                  return Control_Bind.bind(dictMonad.Bind1())(a)(function (v1) {
                      return Control_Applicative.pure(dictMonad.Applicative0())(v(v1));
                  });
              });
          };
      };
  };
  exports["Monad"] = Monad;
  exports["ap"] = ap;
})(PS);
(function(exports) {
  "use strict";

  //------------------------------------------------------------------------------
  // Array creation --------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.range = function (start) {
    return function (end) {
      var step = start > end ? -1 : 1;
      var result = new Array(step * (end - start) + 1);
      var i = start, n = 0;
      while (i !== end) {
        result[n++] = i;
        i += step;
      }
      result[n] = i;
      return result;
    };
  };   

  //------------------------------------------------------------------------------
  // Array size ------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.length = function (xs) {
    return xs.length;
  };

  exports.snoc = function (l) {
    return function (e) {
      var l1 = l.slice();
      l1.push(e);
      return l1;
    };
  };

  //------------------------------------------------------------------------------
  // Indexed operations ----------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.indexImpl = function (just) {
    return function (nothing) {
      return function (xs) {
        return function (i) {
          return i < 0 || i >= xs.length ? nothing :  just(xs[i]);
        };
      };
    };
  };

  exports._updateAt = function (just) {
    return function (nothing) {
      return function (i) {
        return function (a) {
          return function (l) {
            if (i < 0 || i >= l.length) return nothing;
            var l1 = l.slice();
            l1[i] = a;
            return just(l1);
          };
        };
      };
    };
  };

  exports.concat = function (xss) {
    if (xss.length <= 10000) {
      // This method is faster, but it crashes on big arrays.
      // So we use it when can and fallback to simple variant otherwise.
      return Array.prototype.concat.apply([], xss);
    }

    var result = [];
    for (var i = 0, l = xss.length; i < l; i++) {
      var xs = xss[i];
      for (var j = 0, m = xs.length; j < m; j++) {
        result.push(xs[j]);
      }
    }
    return result;
  };

  //------------------------------------------------------------------------------
  // Subarrays -------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.slice = function (s) {
    return function (e) {
      return function (l) {
        return l.slice(s, e);
      };
    };
  };

  //------------------------------------------------------------------------------
  // Zipping ---------------------------------------------------------------------
  //------------------------------------------------------------------------------

  exports.zipWith = function (f) {
    return function (xs) {
      return function (ys) {
        var l = xs.length < ys.length ? xs.length : ys.length;
        var result = new Array(l);
        for (var i = 0; i < l; i++) {
          result[i] = f(xs[i])(ys[i]);
        }
        return result;
      };
    };
  };
})(PS["Data.Array"] = PS["Data.Array"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Boolean"] = $PS["Data.Boolean"] || {};
  var exports = $PS["Data.Boolean"];
  var otherwise = true;
  exports["otherwise"] = otherwise;
})(PS);
(function(exports) {
  "use strict";

  exports.arrayMap = function (f) {
    return function (arr) {
      var l = arr.length;
      var result = new Array(l);
      for (var i = 0; i < l; i++) {
        result[i] = f(arr[i]);
      }
      return result;
    };
  };
})(PS["Data.Functor"] = PS["Data.Functor"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Functor"] = $PS["Data.Functor"] || {};
  var exports = $PS["Data.Functor"];
  var $foreign = $PS["Data.Functor"];
  var Control_Semigroupoid = $PS["Control.Semigroupoid"];
  var Functor = function (map) {
      this.map = map;
  };
  var map = function (dict) {
      return dict.map;
  };
  var functorFn = new Functor(Control_Semigroupoid.compose(Control_Semigroupoid.semigroupoidFn));
  var functorArray = new Functor($foreign.arrayMap);
  exports["Functor"] = Functor;
  exports["map"] = map;
  exports["functorFn"] = functorFn;
  exports["functorArray"] = functorArray;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Maybe"] = $PS["Data.Maybe"] || {};
  var exports = $PS["Data.Maybe"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];
  var Control_Bind = $PS["Control.Bind"];
  var Control_Category = $PS["Control.Category"];
  var Data_Functor = $PS["Data.Functor"];          
  var Nothing = (function () {
      function Nothing() {

      };
      Nothing.value = new Nothing();
      return Nothing;
  })();
  var Just = (function () {
      function Just(value0) {
          this.value0 = value0;
      };
      Just.create = function (value0) {
          return new Just(value0);
      };
      return Just;
  })();
  var maybe = function (v) {
      return function (v1) {
          return function (v2) {
              if (v2 instanceof Nothing) {
                  return v;
              };
              if (v2 instanceof Just) {
                  return v1(v2.value0);
              };
              throw new Error("Failed pattern match at Data.Maybe (line 217, column 1 - line 217, column 51): " + [ v.constructor.name, v1.constructor.name, v2.constructor.name ]);
          };
      };
  };                                                      
  var functorMaybe = new Data_Functor.Functor(function (v) {
      return function (v1) {
          if (v1 instanceof Just) {
              return new Just(v(v1.value0));
          };
          return Nothing.value;
      };
  });
  var fromMaybe = function (a) {
      return maybe(a)(Control_Category.identity(Control_Category.categoryFn));
  };
  var fromJust = function (dictPartial) {
      return function (v) {
          if (v instanceof Just) {
              return v.value0;
          };
          throw new Error("Failed pattern match at Data.Maybe (line 268, column 1 - line 268, column 46): " + [ v.constructor.name ]);
      };
  };
  var applyMaybe = new Control_Apply.Apply(function () {
      return functorMaybe;
  }, function (v) {
      return function (v1) {
          if (v instanceof Just) {
              return Data_Functor.map(functorMaybe)(v.value0)(v1);
          };
          if (v instanceof Nothing) {
              return Nothing.value;
          };
          throw new Error("Failed pattern match at Data.Maybe (line 67, column 1 - line 69, column 30): " + [ v.constructor.name, v1.constructor.name ]);
      };
  });
  var bindMaybe = new Control_Bind.Bind(function () {
      return applyMaybe;
  }, function (v) {
      return function (v1) {
          if (v instanceof Just) {
              return v1(v.value0);
          };
          if (v instanceof Nothing) {
              return Nothing.value;
          };
          throw new Error("Failed pattern match at Data.Maybe (line 125, column 1 - line 127, column 28): " + [ v.constructor.name, v1.constructor.name ]);
      };
  });
  var applicativeMaybe = new Control_Applicative.Applicative(function () {
      return applyMaybe;
  }, Just.create);
  exports["Nothing"] = Nothing;
  exports["Just"] = Just;
  exports["maybe"] = maybe;
  exports["fromMaybe"] = fromMaybe;
  exports["fromJust"] = fromJust;
  exports["functorMaybe"] = functorMaybe;
  exports["applyMaybe"] = applyMaybe;
  exports["applicativeMaybe"] = applicativeMaybe;
  exports["bindMaybe"] = bindMaybe;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Array"] = $PS["Data.Array"] || {};
  var exports = $PS["Data.Array"];
  var $foreign = $PS["Data.Array"];
  var Data_Boolean = $PS["Data.Boolean"];
  var Data_Maybe = $PS["Data.Maybe"];
  var updateAt = $foreign["_updateAt"](Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var $$null = function (xs) {
      return $foreign.length(xs) === 0;
  };
  var mapWithIndex = function (f) {
      return function (xs) {
          return $foreign.zipWith(f)($foreign.range(0)($foreign.length(xs) - 1 | 0))(xs);
      };
  };                                                                                     
  var init = function (xs) {
      if ($$null(xs)) {
          return Data_Maybe.Nothing.value;
      };
      if (Data_Boolean.otherwise) {
          return new Data_Maybe.Just($foreign.slice(0)($foreign.length(xs) - 1 | 0)(xs));
      };
      throw new Error("Failed pattern match at Data.Array (line 323, column 1 - line 323, column 45): " + [ xs.constructor.name ]);
  };
  var index = $foreign.indexImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
  var last = function (xs) {
      return index(xs)($foreign.length(xs) - 1 | 0);
  };
  var head = function (xs) {
      return index(xs)(0);
  };
  exports["null"] = $$null;
  exports["head"] = head;
  exports["last"] = last;
  exports["init"] = init;
  exports["index"] = index;
  exports["updateAt"] = updateAt;
  exports["mapWithIndex"] = mapWithIndex;
  exports["range"] = $foreign.range;
  exports["length"] = $foreign.length;
  exports["snoc"] = $foreign.snoc;
  exports["concat"] = $foreign.concat;
})(PS);
(function(exports) {
  "use strict";

  // module Unsafe.Coerce

  exports.unsafeCoerce = function (x) {
    return x;
  };
})(PS["Unsafe.Coerce"] = PS["Unsafe.Coerce"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Unsafe.Coerce"] = $PS["Unsafe.Coerce"] || {};
  var exports = $PS["Unsafe.Coerce"];
  var $foreign = $PS["Unsafe.Coerce"];
  exports["unsafeCoerce"] = $foreign.unsafeCoerce;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Array.NonEmpty"] = $PS["Data.Array.NonEmpty"] || {};
  var exports = $PS["Data.Array.NonEmpty"];
  var Data_Array = $PS["Data.Array"];
  var Data_Boolean = $PS["Data.Boolean"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Unsafe_Coerce = $PS["Unsafe.Coerce"];         
  var unsafeFromArray = Unsafe_Coerce.unsafeCoerce;
  var toArray = Unsafe_Coerce.unsafeCoerce;
  var fromArray = function (xs) {
      if (Data_Array.length(xs) > 0) {
          return new Data_Maybe.Just(unsafeFromArray(xs));
      };
      if (Data_Boolean.otherwise) {
          return Data_Maybe.Nothing.value;
      };
      throw new Error("Failed pattern match at Data.Array.NonEmpty (line 134, column 1 - line 134, column 58): " + [ xs.constructor.name ]);
  };
  var adaptMaybe = function (f) {
      var $64 = Data_Maybe.fromJust();
      return function ($65) {
          return $64(f(toArray($65)));
      };
  };
  var head = adaptMaybe(Data_Array.head);
  var init = adaptMaybe(Data_Array.init);
  var last = adaptMaybe(Data_Array.last);    
  var adaptAny = function (f) {
      return function ($67) {
          return f(toArray($67));
      };
  };                                     
  var length = adaptAny(Data_Array.length);
  exports["fromArray"] = fromArray;
  exports["toArray"] = toArray;
  exports["length"] = length;
  exports["head"] = head;
  exports["last"] = last;
  exports["init"] = init;
})(PS);
(function(exports) {
  "use strict";

  exports.intSub = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x - y | 0;
    };
  };
})(PS["Data.Ring"] = PS["Data.Ring"] || {});
(function(exports) {
  "use strict";

  exports.intAdd = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x + y | 0;
    };
  };

  exports.intMul = function (x) {
    return function (y) {
      /* jshint bitwise: false */
      return x * y | 0;
    };
  };
})(PS["Data.Semiring"] = PS["Data.Semiring"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Semiring"] = $PS["Data.Semiring"] || {};
  var exports = $PS["Data.Semiring"];
  var $foreign = $PS["Data.Semiring"];
  var Semiring = function (add, mul, one, zero) {
      this.add = add;
      this.mul = mul;
      this.one = one;
      this.zero = zero;
  };
  var zero = function (dict) {
      return dict.zero;
  };                                                                            
  var semiringInt = new Semiring($foreign.intAdd, $foreign.intMul, 1, 0);
  var one = function (dict) {
      return dict.one;
  };
  var mul = function (dict) {
      return dict.mul;
  };
  var add = function (dict) {
      return dict.add;
  };
  exports["Semiring"] = Semiring;
  exports["add"] = add;
  exports["zero"] = zero;
  exports["mul"] = mul;
  exports["one"] = one;
  exports["semiringInt"] = semiringInt;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Ring"] = $PS["Data.Ring"] || {};
  var exports = $PS["Data.Ring"];
  var $foreign = $PS["Data.Ring"];
  var Data_Semiring = $PS["Data.Semiring"];
  var Ring = function (Semiring0, sub) {
      this.Semiring0 = Semiring0;
      this.sub = sub;
  };
  var sub = function (dict) {
      return dict.sub;
  };                  
  var ringInt = new Ring(function () {
      return Data_Semiring.semiringInt;
  }, $foreign.intSub);
  exports["Ring"] = Ring;
  exports["sub"] = sub;
  exports["ringInt"] = ringInt;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.CommutativeRing"] = $PS["Data.CommutativeRing"] || {};
  var exports = $PS["Data.CommutativeRing"];
  var Data_Ring = $PS["Data.Ring"];
  var CommutativeRing = function (Ring0) {
      this.Ring0 = Ring0;
  }; 
  var commutativeRingInt = new CommutativeRing(function () {
      return Data_Ring.ringInt;
  });
  exports["CommutativeRing"] = CommutativeRing;
  exports["commutativeRingInt"] = commutativeRingInt;
})(PS);
(function(exports) {
  "use strict";

  exports.boolConj = function (b1) {
    return function (b2) {
      return b1 && b2;
    };
  };

  exports.boolDisj = function (b1) {
    return function (b2) {
      return b1 || b2;
    };
  };

  exports.boolNot = function (b) {
    return !b;
  };
})(PS["Data.HeytingAlgebra"] = PS["Data.HeytingAlgebra"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.HeytingAlgebra"] = $PS["Data.HeytingAlgebra"] || {};
  var exports = $PS["Data.HeytingAlgebra"];
  var $foreign = $PS["Data.HeytingAlgebra"];
  var HeytingAlgebra = function (conj, disj, ff, implies, not, tt) {
      this.conj = conj;
      this.disj = disj;
      this.ff = ff;
      this.implies = implies;
      this.not = not;
      this.tt = tt;
  };
  var tt = function (dict) {
      return dict.tt;
  };
  var not = function (dict) {
      return dict.not;
  };
  var implies = function (dict) {
      return dict.implies;
  };
  var ff = function (dict) {
      return dict.ff;
  };
  var disj = function (dict) {
      return dict.disj;
  };
  var heytingAlgebraBoolean = new HeytingAlgebra($foreign.boolConj, $foreign.boolDisj, false, function (a) {
      return function (b) {
          return disj(heytingAlgebraBoolean)(not(heytingAlgebraBoolean)(a))(b);
      };
  }, $foreign.boolNot, true);
  var conj = function (dict) {
      return dict.conj;
  };
  exports["HeytingAlgebra"] = HeytingAlgebra;
  exports["tt"] = tt;
  exports["ff"] = ff;
  exports["implies"] = implies;
  exports["conj"] = conj;
  exports["disj"] = disj;
  exports["not"] = not;
  exports["heytingAlgebraBoolean"] = heytingAlgebraBoolean;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Monoid"] = $PS["Data.Monoid"] || {};
  var exports = $PS["Data.Monoid"];
  var Monoid = function (Semigroup0, mempty) {
      this.Semigroup0 = Semigroup0;
      this.mempty = mempty;
  };
  var mempty = function (dict) {
      return dict.mempty;
  };
  exports["Monoid"] = Monoid;
  exports["mempty"] = mempty;
})(PS);
(function(exports) {
  "use strict";

  exports.concatArray = function (xs) {
    return function (ys) {
      if (xs.length === 0) return ys;
      if (ys.length === 0) return xs;
      return xs.concat(ys);
    };
  };
})(PS["Data.Semigroup"] = PS["Data.Semigroup"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Semigroup"] = $PS["Data.Semigroup"] || {};
  var exports = $PS["Data.Semigroup"];
  var $foreign = $PS["Data.Semigroup"];
  var Semigroup = function (append) {
      this.append = append;
  }; 
  var semigroupArray = new Semigroup($foreign.concatArray);
  var append = function (dict) {
      return dict.append;
  };
  exports["Semigroup"] = Semigroup;
  exports["append"] = append;
  exports["semigroupArray"] = semigroupArray;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Monoid.Conj"] = $PS["Data.Monoid.Conj"] || {};
  var exports = $PS["Data.Monoid.Conj"];
  var Data_HeytingAlgebra = $PS["Data.HeytingAlgebra"];
  var Data_Monoid = $PS["Data.Monoid"];
  var Data_Semigroup = $PS["Data.Semigroup"];      
  var Conj = function (x) {
      return x;
  };
  var semigroupConj = function (dictHeytingAlgebra) {
      return new Data_Semigroup.Semigroup(function (v) {
          return function (v1) {
              return Data_HeytingAlgebra.conj(dictHeytingAlgebra)(v)(v1);
          };
      });
  };
  var monoidConj = function (dictHeytingAlgebra) {
      return new Data_Monoid.Monoid(function () {
          return semigroupConj(dictHeytingAlgebra);
      }, Data_HeytingAlgebra.tt(dictHeytingAlgebra));
  };
  exports["Conj"] = Conj;
  exports["semigroupConj"] = semigroupConj;
  exports["monoidConj"] = monoidConj;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Monoid.Disj"] = $PS["Data.Monoid.Disj"] || {};
  var exports = $PS["Data.Monoid.Disj"];
  var Data_HeytingAlgebra = $PS["Data.HeytingAlgebra"];
  var Data_Monoid = $PS["Data.Monoid"];
  var Data_Semigroup = $PS["Data.Semigroup"];      
  var Disj = function (x) {
      return x;
  };
  var semigroupDisj = function (dictHeytingAlgebra) {
      return new Data_Semigroup.Semigroup(function (v) {
          return function (v1) {
              return Data_HeytingAlgebra.disj(dictHeytingAlgebra)(v)(v1);
          };
      });
  };
  var monoidDisj = function (dictHeytingAlgebra) {
      return new Data_Monoid.Monoid(function () {
          return semigroupDisj(dictHeytingAlgebra);
      }, Data_HeytingAlgebra.ff(dictHeytingAlgebra));
  };
  exports["Disj"] = Disj;
  exports["semigroupDisj"] = semigroupDisj;
  exports["monoidDisj"] = monoidDisj;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Newtype"] = $PS["Data.Newtype"] || {};
  var exports = $PS["Data.Newtype"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Monoid_Conj = $PS["Data.Monoid.Conj"];
  var Data_Monoid_Disj = $PS["Data.Monoid.Disj"];                      
  var Newtype = function (unwrap, wrap) {
      this.unwrap = unwrap;
      this.wrap = wrap;
  };
  var wrap = function (dict) {
      return dict.wrap;
  };
  var unwrap = function (dict) {
      return dict.unwrap;
  };                        
  var newtypeDisj = new Newtype(function (v) {
      return v;
  }, Data_Monoid_Disj.Disj);
  var newtypeConj = new Newtype(function (v) {
      return v;
  }, Data_Monoid_Conj.Conj);
  var alaF = function (dictFunctor) {
      return function (dictFunctor1) {
          return function (dictNewtype) {
              return function (dictNewtype1) {
                  return function (v) {
                      return function (f) {
                          var $96 = Data_Functor.map(dictFunctor1)(unwrap(dictNewtype1));
                          var $97 = Data_Functor.map(dictFunctor)(wrap(dictNewtype));
                          return function ($98) {
                              return $96(f($97($98)));
                          };
                      };
                  };
              };
          };
      };
  };
  exports["unwrap"] = unwrap;
  exports["wrap"] = wrap;
  exports["Newtype"] = Newtype;
  exports["alaF"] = alaF;
  exports["newtypeConj"] = newtypeConj;
  exports["newtypeDisj"] = newtypeDisj;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Const"] = $PS["Data.Const"] || {};
  var exports = $PS["Data.Const"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Newtype = $PS["Data.Newtype"];                                          
  var Const = function (x) {
      return x;
  };
  var newtypeConst = new Data_Newtype.Newtype(function (n) {
      return n;
  }, Const);
  var functorConst = new Data_Functor.Functor(function (f) {
      return function (m) {
          return m;
      };
  });
  exports["Const"] = Const;
  exports["newtypeConst"] = newtypeConst;
  exports["functorConst"] = functorConst;
})(PS);
(function(exports) {
  "use strict";

  var refEq = function (r1) {
    return function (r2) {
      return r1 === r2;
    };
  };                            
  exports.eqIntImpl = refEq;
})(PS["Data.Eq"] = PS["Data.Eq"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Eq"] = $PS["Data.Eq"] || {};
  var exports = $PS["Data.Eq"];
  var $foreign = $PS["Data.Eq"];
  var Eq = function (eq) {
      this.eq = eq;
  };                                           
  var eqInt = new Eq($foreign.eqIntImpl);
  var eq = function (dict) {
      return dict.eq;
  };
  exports["Eq"] = Eq;
  exports["eq"] = eq;
  exports["eqInt"] = eqInt;
})(PS);
(function(exports) {
  "use strict";

  exports.intDegree = function (x) {
    return Math.min(Math.abs(x), 2147483647);
  };

  // See the Euclidean definition in
  // https://en.m.wikipedia.org/wiki/Modulo_operation.
  exports.intDiv = function (x) {
    return function (y) {
      if (y === 0) return 0;
      return y > 0 ? Math.floor(x / y) : -Math.floor(x / -y);
    };
  };

  exports.intMod = function (x) {
    return function (y) {
      if (y === 0) return 0;
      var yy = Math.abs(y);
      return ((x % yy) + yy) % yy;
    };
  };
})(PS["Data.EuclideanRing"] = PS["Data.EuclideanRing"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.EuclideanRing"] = $PS["Data.EuclideanRing"] || {};
  var exports = $PS["Data.EuclideanRing"];
  var $foreign = $PS["Data.EuclideanRing"];
  var Data_CommutativeRing = $PS["Data.CommutativeRing"];  
  var EuclideanRing = function (CommutativeRing0, degree, div, mod) {
      this.CommutativeRing0 = CommutativeRing0;
      this.degree = degree;
      this.div = div;
      this.mod = mod;
  };
  var mod = function (dict) {
      return dict.mod;
  }; 
  var euclideanRingInt = new EuclideanRing(function () {
      return Data_CommutativeRing.commutativeRingInt;
  }, $foreign.intDegree, $foreign.intDiv, $foreign.intMod);
  var div = function (dict) {
      return dict.div;
  };
  var degree = function (dict) {
      return dict.degree;
  };
  exports["EuclideanRing"] = EuclideanRing;
  exports["degree"] = degree;
  exports["div"] = div;
  exports["mod"] = mod;
  exports["euclideanRingInt"] = euclideanRingInt;
})(PS);
(function(exports) {
  "use strict";

  exports.foldrArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = len - 1; i >= 0; i--) {
          acc = f(xs[i])(acc);
        }
        return acc;
      };
    };
  };

  exports.foldlArray = function (f) {
    return function (init) {
      return function (xs) {
        var acc = init;
        var len = xs.length;
        for (var i = 0; i < len; i++) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      };
    };
  };
})(PS["Data.Foldable"] = PS["Data.Foldable"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Foldable"] = $PS["Data.Foldable"] || {};
  var exports = $PS["Data.Foldable"];
  var $foreign = $PS["Data.Foldable"];
  var Data_Eq = $PS["Data.Eq"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_HeytingAlgebra = $PS["Data.HeytingAlgebra"];
  var Data_Monoid = $PS["Data.Monoid"];
  var Data_Monoid_Conj = $PS["Data.Monoid.Conj"];
  var Data_Monoid_Disj = $PS["Data.Monoid.Disj"];
  var Data_Newtype = $PS["Data.Newtype"];
  var Data_Semigroup = $PS["Data.Semigroup"];      
  var Foldable = function (foldMap, foldl, foldr) {
      this.foldMap = foldMap;
      this.foldl = foldl;
      this.foldr = foldr;
  };
  var foldr = function (dict) {
      return dict.foldr;
  };
  var foldl = function (dict) {
      return dict.foldl;
  }; 
  var foldMapDefaultR = function (dictFoldable) {
      return function (dictMonoid) {
          return function (f) {
              return foldr(dictFoldable)(function (x) {
                  return function (acc) {
                      return Data_Semigroup.append(dictMonoid.Semigroup0())(f(x))(acc);
                  };
              })(Data_Monoid.mempty(dictMonoid));
          };
      };
  };
  var foldableArray = new Foldable(function (dictMonoid) {
      return foldMapDefaultR(foldableArray)(dictMonoid);
  }, $foreign.foldlArray, $foreign.foldrArray);
  var foldMap = function (dict) {
      return dict.foldMap;
  };
  var any = function (dictFoldable) {
      return function (dictHeytingAlgebra) {
          return Data_Newtype.alaF(Data_Functor.functorFn)(Data_Functor.functorFn)(Data_Newtype.newtypeDisj)(Data_Newtype.newtypeDisj)(Data_Monoid_Disj.Disj)(foldMap(dictFoldable)(Data_Monoid_Disj.monoidDisj(dictHeytingAlgebra)));
      };
  };
  var elem = function (dictFoldable) {
      return function (dictEq) {
          var $204 = any(dictFoldable)(Data_HeytingAlgebra.heytingAlgebraBoolean);
          var $205 = Data_Eq.eq(dictEq);
          return function ($206) {
              return $204($205($206));
          };
      };
  };
  var all = function (dictFoldable) {
      return function (dictHeytingAlgebra) {
          return Data_Newtype.alaF(Data_Functor.functorFn)(Data_Functor.functorFn)(Data_Newtype.newtypeConj)(Data_Newtype.newtypeConj)(Data_Monoid_Conj.Conj)(foldMap(dictFoldable)(Data_Monoid_Conj.monoidConj(dictHeytingAlgebra)));
      };
  };
  exports["Foldable"] = Foldable;
  exports["foldr"] = foldr;
  exports["foldl"] = foldl;
  exports["foldMap"] = foldMap;
  exports["foldMapDefaultR"] = foldMapDefaultR;
  exports["all"] = all;
  exports["any"] = any;
  exports["elem"] = elem;
  exports["foldableArray"] = foldableArray;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Function"] = $PS["Data.Function"] || {};
  var exports = $PS["Data.Function"];
  var flip = function (f) {
      return function (b) {
          return function (a) {
              return f(a)(b);
          };
      };
  };
  var $$const = function (a) {
      return function (v) {
          return a;
      };
  };
  exports["flip"] = flip;
  exports["const"] = $$const;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Identity"] = $PS["Data.Identity"] || {};
  var exports = $PS["Data.Identity"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Newtype = $PS["Data.Newtype"];          
  var Identity = function (x) {
      return x;
  };
  var newtypeIdentity = new Data_Newtype.Newtype(function (n) {
      return n;
  }, Identity);
  var functorIdentity = new Data_Functor.Functor(function (f) {
      return function (m) {
          return f(m);
      };
  });
  exports["Identity"] = Identity;
  exports["newtypeIdentity"] = newtypeIdentity;
  exports["functorIdentity"] = functorIdentity;
})(PS);
(function(exports) {
  "use strict";

  exports.toNumber = function (n) {
    return n;
  };
})(PS["Data.Int"] = PS["Data.Int"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Int"] = $PS["Data.Int"] || {};
  var exports = $PS["Data.Int"];
  var $foreign = $PS["Data.Int"];
  exports["toNumber"] = $foreign.toNumber;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Profunctor"] = $PS["Data.Profunctor"] || {};
  var exports = $PS["Data.Profunctor"];
  var Control_Category = $PS["Control.Category"];        
  var Profunctor = function (dimap) {
      this.dimap = dimap;
  };
  var profunctorFn = new Profunctor(function (a2b) {
      return function (c2d) {
          return function (b2c) {
              return function ($9) {
                  return c2d(b2c(a2b($9)));
              };
          };
      };
  });
  var dimap = function (dict) {
      return dict.dimap;
  };
  var rmap = function (dictProfunctor) {
      return function (b2c) {
          return dimap(dictProfunctor)(Control_Category.identity(Control_Category.categoryFn))(b2c);
      };
  };
  exports["dimap"] = dimap;
  exports["Profunctor"] = Profunctor;
  exports["rmap"] = rmap;
  exports["profunctorFn"] = profunctorFn;
})(PS);
(function(exports) {
  "use strict";

  exports.showIntImpl = function (n) {
    return n.toString();
  };

  exports.showNumberImpl = function (n) {
    var str = n.toString();
    return isNaN(str + ".0") ? str : str + ".0";
  };
})(PS["Data.Show"] = PS["Data.Show"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Show"] = $PS["Data.Show"] || {};
  var exports = $PS["Data.Show"];
  var $foreign = $PS["Data.Show"];
  var Show = function (show) {
      this.show = show;
  };
  var showNumber = new Show($foreign.showNumberImpl);
  var showInt = new Show($foreign.showIntImpl);  
  var showBoolean = new Show(function (v) {
      if (v) {
          return "true";
      };
      if (!v) {
          return "false";
      };
      throw new Error("Failed pattern match at Data.Show (line 20, column 1 - line 22, column 23): " + [ v.constructor.name ]);
  });
  var show = function (dict) {
      return dict.show;
  };
  exports["Show"] = Show;
  exports["show"] = show;
  exports["showBoolean"] = showBoolean;
  exports["showInt"] = showInt;
  exports["showNumber"] = showNumber;
})(PS);
(function(exports) {
  "use strict";

  // jshint maxparams: 3

  exports.traverseArrayImpl = function () {
    function array1(a) {
      return [a];
    }

    function array2(a) {
      return function (b) {
        return [a, b];
      };
    }

    function array3(a) {
      return function (b) {
        return function (c) {
          return [a, b, c];
        };
      };
    }

    function concat2(xs) {
      return function (ys) {
        return xs.concat(ys);
      };
    }

    return function (apply) {
      return function (map) {
        return function (pure) {
          return function (f) {
            return function (array) {
              function go(bot, top) {
                switch (top - bot) {
                case 0: return pure([]);
                case 1: return map(array1)(f(array[bot]));
                case 2: return apply(map(array2)(f(array[bot])))(f(array[bot + 1]));
                case 3: return apply(apply(map(array3)(f(array[bot])))(f(array[bot + 1])))(f(array[bot + 2]));
                default:
                  // This slightly tricky pivot selection aims to produce two
                  // even-length partitions where possible.
                  var pivot = bot + Math.floor((top - bot) / 4) * 2;
                  return apply(map(concat2)(go(bot, pivot)))(go(pivot, top));
                }
              }
              return go(0, array.length);
            };
          };
        };
      };
    };
  }();
})(PS["Data.Traversable"] = PS["Data.Traversable"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Traversable"] = $PS["Data.Traversable"] || {};
  var exports = $PS["Data.Traversable"];
  var $foreign = $PS["Data.Traversable"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];
  var Control_Category = $PS["Control.Category"];
  var Data_Foldable = $PS["Data.Foldable"];
  var Data_Functor = $PS["Data.Functor"];                                                      
  var Traversable = function (Foldable1, Functor0, sequence, traverse) {
      this.Foldable1 = Foldable1;
      this.Functor0 = Functor0;
      this.sequence = sequence;
      this.traverse = traverse;
  };
  var traverse = function (dict) {
      return dict.traverse;
  }; 
  var sequenceDefault = function (dictTraversable) {
      return function (dictApplicative) {
          return traverse(dictTraversable)(dictApplicative)(Control_Category.identity(Control_Category.categoryFn));
      };
  };
  var traversableArray = new Traversable(function () {
      return Data_Foldable.foldableArray;
  }, function () {
      return Data_Functor.functorArray;
  }, function (dictApplicative) {
      return sequenceDefault(traversableArray)(dictApplicative);
  }, function (dictApplicative) {
      return $foreign.traverseArrayImpl(Control_Apply.apply(dictApplicative.Apply0()))(Data_Functor.map((dictApplicative.Apply0()).Functor0()))(Control_Applicative.pure(dictApplicative));
  });
  var sequence = function (dict) {
      return dict.sequence;
  };
  exports["Traversable"] = Traversable;
  exports["traverse"] = traverse;
  exports["sequence"] = sequence;
  exports["sequenceDefault"] = sequenceDefault;
  exports["traversableArray"] = traversableArray;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Data.Tuple"] = $PS["Data.Tuple"] || {};
  var exports = $PS["Data.Tuple"];                         
  var Tuple = (function () {
      function Tuple(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Tuple.create = function (value0) {
          return function (value1) {
              return new Tuple(value0, value1);
          };
      };
      return Tuple;
  })();
  var uncurry = function (f) {
      return function (v) {
          return f(v.value0)(v.value1);
      };
  };
  exports["Tuple"] = Tuple;
  exports["uncurry"] = uncurry;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Lib.Core"] = $PS["Lib.Core"] || {};
  var exports = $PS["Lib.Core"];
  var Control_Bind = $PS["Control.Bind"];
  var Data_Array = $PS["Data.Array"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Maybe = $PS["Data.Maybe"];                
  var swap = function (i) {
      return function (j) {
          return function (array) {
              return Data_Maybe.fromMaybe(array)(Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array.index(array)(i))(function (v) {
                  return Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array.index(array)(j))(function (v1) {
                      return Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array.updateAt(i)(v1)(array))(Data_Array.updateAt(j)(v));
                  });
              }));
          };
      };
  };
  var repeat = function (v) {
      return function (v1) {
          if (v === 0) {
              return [  ];
          };
          return Data_Functor.map(Data_Functor.functorArray)(v1)(Data_Array.range(0)(v - 1 | 0));
      };
  };
  exports["repeat"] = repeat;
  exports["swap"] = swap;
})(PS);
(function(exports) {
  exports.nextSeed = seed => ((1 + Math.sin(seed)) * (1 << 30)) | 0;
})(PS["Lib.Random"] = PS["Lib.Random"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Optic.Getter"] = $PS["Optic.Getter"] || {};
  var exports = $PS["Optic.Getter"];
  var Data_Const = $PS["Data.Const"];
  var Data_Function = $PS["Data.Function"];
  var Data_Newtype = $PS["Data.Newtype"];                      
  var view = function (asa) {
      return function (s) {
          return Data_Newtype.unwrap(Data_Const.newtypeConst)(asa(Data_Const.Const)(s));
      };
  };
  var weiv = Data_Function.flip(view);
  exports["view"] = view;
  exports["weiv"] = weiv;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Optic.Setter"] = $PS["Optic.Setter"] || {};
  var exports = $PS["Optic.Setter"];
  var Data_Function = $PS["Data.Function"];
  var Data_Identity = $PS["Data.Identity"];
  var Data_Newtype = $PS["Data.Newtype"];
  var Data_Profunctor = $PS["Data.Profunctor"];
  var set = function (stab) {
      return function (b) {
          var $25 = Data_Newtype.unwrap(Data_Identity.newtypeIdentity);
          var $26 = stab((function () {
              var $28 = Data_Function["const"](b);
              return function ($29) {
                  return Data_Identity.Identity($28($29));
              };
          })());
          return function ($27) {
              return $25($26($27));
          };
      };
  };
  var over = function (dictProfunctor) {
      return function (pstab) {
          return function (pab) {
              var $30 = Data_Newtype.unwrap(Data_Identity.newtypeIdentity);
              var $31 = pstab(Data_Profunctor.rmap(dictProfunctor)(Data_Identity.Identity)(pab));
              return function ($32) {
                  return $30($31($32));
              };
          };
      };
  };
  exports["over"] = over;
  exports["set"] = set;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Lib.Random"] = $PS["Lib.Random"] || {};
  var exports = $PS["Lib.Random"];
  var $foreign = $PS["Lib.Random"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Apply = $PS["Control.Apply"];
  var Control_Bind = $PS["Control.Bind"];
  var Control_Monad = $PS["Control.Monad"];
  var Data_Array = $PS["Data.Array"];
  var Data_Const = $PS["Data.Const"];
  var Data_EuclideanRing = $PS["Data.EuclideanRing"];
  var Data_Foldable = $PS["Data.Foldable"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Identity = $PS["Data.Identity"];
  var Data_Traversable = $PS["Data.Traversable"];
  var Data_Tuple = $PS["Data.Tuple"];
  var Lib_Core = $PS["Lib.Core"];
  var Optic_Getter = $PS["Optic.Getter"];
  var Optic_Setter = $PS["Optic.Setter"];
  var Random = function (x) {
      return x;
  };
  var run = function (lens) {
      return function (st) {
          return function (v) {
              var v1 = v(Optic_Getter.weiv(st)(lens(Data_Const.functorConst)));
              return Optic_Setter.set(lens(Data_Identity.functorIdentity))(v1.value1)(v1.value0);
          };
      };
  };
  var intFromSeed = function (v) {
      return function (max) {
          return Data_EuclideanRing.mod(Data_EuclideanRing.euclideanRingInt)(v)(max);
      };
  };
  var randomInt = function (n) {
      return function (seed) {
          return new Data_Tuple.Tuple(intFromSeed(seed)(n), $foreign.nextSeed(seed));
      };
  };
  var functorRandom = new Data_Functor.Functor(function (f) {
      return function (v) {
          return function (seed) {
              var v1 = v(seed);
              return new Data_Tuple.Tuple(f(v1.value0), v1.value1);
          };
      };
  });
  var monadRandom = new Control_Monad.Monad(function () {
      return applicativeRandom;
  }, function () {
      return bindRandom;
  });
  var bindRandom = new Control_Bind.Bind(function () {
      return applyRandom;
  }, function (v) {
      return function (f) {
          return function (seed) {
              var v1 = v(seed);
              var v2 = f(v1.value0);
              return v2(v1.value1);
          };
      };
  });
  var applyRandom = new Control_Apply.Apply(function () {
      return functorRandom;
  }, Control_Monad.ap(monadRandom));
  var applicativeRandom = new Control_Applicative.Applicative(function () {
      return applyRandom;
  }, function (x) {
      return Random(function (seed) {
          return new Data_Tuple.Tuple(x, seed);
      });
  });
  var randomInts$prime = function (n) {
      return function (fn) {
          return Data_Traversable.sequence(Data_Traversable.traversableArray)(applicativeRandom)(Lib_Core.repeat(n)(function (i) {
              return randomInt(fn(i));
          }));
      };
  };
  var shuffle = function (array) {
      var n = Data_Array.length(array);
      return Control_Bind.bind(bindRandom)(randomInts$prime(n - 1 | 0)(function (x) {
          return n - x | 0;
      }))(function (v) {
          return Control_Applicative.pure(applicativeRandom)(Data_Foldable.foldr(Data_Foldable.foldableArray)(Data_Tuple.uncurry(Lib_Core.swap))(array)(Data_Array.mapWithIndex(function (i) {
              return function (j) {
                  return new Data_Tuple.Tuple(i, i + j | 0);
              };
          })(v)));
      });
  };
  exports["Random"] = Random;
  exports["intFromSeed"] = intFromSeed;
  exports["randomInt"] = randomInt;
  exports["shuffle"] = shuffle;
  exports["run"] = run;
  exports["monadRandom"] = monadRandom;
  exports["functorRandom"] = functorRandom;
  exports["applyRandom"] = applyRandom;
  exports["applicativeRandom"] = applicativeRandom;
  exports["bindRandom"] = bindRandom;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Lib.Game"] = $PS["Lib.Game"] || {};
  var exports = $PS["Lib.Game"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];
  var Data_Array = $PS["Data.Array"];
  var Data_Array_NonEmpty = $PS["Data.Array.NonEmpty"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Lib_Random = $PS["Lib.Random"];                
  var SoloMode = (function () {
      function SoloMode() {

      };
      SoloMode.value = new SoloMode();
      return SoloMode;
  })();
  var DuelMode = (function () {
      function DuelMode() {

      };
      DuelMode.value = new DuelMode();
      return DuelMode;
  })();
  var Rules = (function () {
      function Rules() {

      };
      Rules.value = new Rules();
      return Rules;
  })();
  var NoDialog = (function () {
      function NoDialog() {

      };
      NoDialog.value = new NoDialog();
      return NoDialog;
  })();
  var ConfirmNewGame = (function () {
      function ConfirmNewGame(value0) {
          this.value0 = value0;
      };
      ConfirmNewGame.create = function (value0) {
          return new ConfirmNewGame(value0);
      };
      return ConfirmNewGame;
  })();
  var St = (function () {
      function St(value0) {
          this.value0 = value0;
      };
      St.create = function (value0) {
          return new St(value0);
      };
      return St;
  })();
  var Game = function (canPlay, initialPosition, isLevelFinished, play) {
      this.canPlay = canPlay;
      this.initialPosition = initialPosition;
      this.isLevelFinished = isLevelFinished;
      this.play = play;
  };
  var setDialog = function (dialog) {
      return function (v) {
          return new St((function () {
              var $29 = {};
              for (var $30 in v.value0) {
                  if ({}.hasOwnProperty.call(v.value0, $30)) {
                      $29[$30] = v["value0"][$30];
                  };
              };
              $29.dialog = dialog;
              return $29;
          })());
      };
  };
  var reset = function (v) {
      return Data_Maybe.fromMaybe(new St(v.value0))(Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array_NonEmpty.fromArray(v.value0.history))(function (v1) {
          return Control_Applicative.pure(Data_Maybe.applicativeMaybe)(new St((function () {
              var $35 = {};
              for (var $36 in v.value0) {
                  if ({}.hasOwnProperty.call(v.value0, $36)) {
                      $35[$36] = v["value0"][$36];
                  };
              };
              $35.position = Data_Array_NonEmpty.head(v1);
              $35.history = [  ];
              $35.redoHistory = [  ];
              $35.turn = 0;
              return $35;
          })()));
      }));
  };
  var play = function (dict) {
      return dict.play;
  };
  var isLevelFinished = function (dict) {
      return dict.isLevelFinished;
  };
  var initialPosition = function (dict) {
      return dict.initialPosition;
  };
  var newGame = function (dictGame) {
      return function (f) {
          return function (v) {
              var v1 = f(v);
              return Control_Bind.bind(Lib_Random.bindRandom)(initialPosition(dictGame)(v1))(function (v2) {
                  var st3 = new St((function () {
                      var $43 = {};
                      for (var $44 in v1.value0) {
                          if ({}.hasOwnProperty.call(v1.value0, $44)) {
                              $43[$44] = v1["value0"][$44];
                          };
                      };
                      $43.position = v2;
                      $43.history = [  ];
                      $43.redoHistory = [  ];
                      return $43;
                  })());
                  var $46 = Data_Array["null"](v1.value0.history);
                  if ($46) {
                      return Control_Applicative.pure(Lib_Random.applicativeRandom)(st3);
                  };
                  return Control_Applicative.pure(Lib_Random.applicativeRandom)(setDialog(new ConfirmNewGame(st3))(v));
              });
          };
      };
  };
  var newGame$prime = function (dictGame) {
      return function (f) {
          return function (val) {
              return newGame(dictGame)(f(val));
          };
      };
  };
  var confirmNewGame = function (st) {
      return function (v) {
          return setDialog(NoDialog.value)(st);
      };
  };
  var changeTurn = function (v) {
      if (v.value0.mode instanceof DuelMode) {
          return new St((function () {
              var $51 = {};
              for (var $52 in v.value0) {
                  if ({}.hasOwnProperty.call(v.value0, $52)) {
                      $51[$52] = v["value0"][$52];
                  };
              };
              $51.turn = 1 - v.value0.turn | 0;
              return $51;
          })());
      };
      return new St(v.value0);
  };
  var redo = function (v) {
      return Data_Maybe.fromMaybe(new St(v.value0))(Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array_NonEmpty.fromArray(v.value0.redoHistory))(function (v1) {
          return Control_Applicative.pure(Data_Maybe.applicativeMaybe)(changeTurn(new St((function () {
              var $57 = {};
              for (var $58 in v.value0) {
                  if ({}.hasOwnProperty.call(v.value0, $58)) {
                      $57[$58] = v["value0"][$58];
                  };
              };
              $57.position = Data_Array_NonEmpty.last(v1);
              $57.redoHistory = Data_Array_NonEmpty.init(v1);
              $57.history = Data_Array.snoc(v.value0.history)(v.value0.position);
              return $57;
          })())));
      }));
  };
  var undo = function (v) {
      return Data_Maybe.fromMaybe(new St(v.value0))(Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array_NonEmpty.fromArray(v.value0.history))(function (v1) {
          return Control_Applicative.pure(Data_Maybe.applicativeMaybe)(changeTurn(new St((function () {
              var $63 = {};
              for (var $64 in v.value0) {
                  if ({}.hasOwnProperty.call(v.value0, $64)) {
                      $63[$64] = v["value0"][$64];
                  };
              };
              $63.position = Data_Array_NonEmpty.last(v1);
              $63.history = Data_Array_NonEmpty.init(v1);
              $63.redoHistory = Data_Array.snoc(v.value0.redoHistory)(v.value0.position);
              return $63;
          })())));
      }));
  };
  var canPlay = function (dict) {
      return dict.canPlay;
  };
  var _play = function (dictGame) {
      return function (v) {
          return function (v1) {
              var $69 = canPlay(dictGame)(v1)(v.move);
              if ($69) {
                  var v2 = new St((function () {
                      var $70 = {};
                      for (var $71 in v1.value0) {
                          if ({}.hasOwnProperty.call(v1.value0, $71)) {
                              $70[$71] = v1["value0"][$71];
                          };
                      };
                      $70.position = play(dictGame)(v1)(v.move);
                      $70.history = Data_Array.snoc(v1.value0.history)(v1.value0.position);
                      $70.redoHistory = [  ];
                      return $70;
                  })());
                  return new St((function () {
                      var $74 = {};
                      for (var $75 in v2.value0) {
                          if ({}.hasOwnProperty.call(v2.value0, $75)) {
                              $74[$75] = v2["value0"][$75];
                          };
                      };
                      $74.levelFinished = isLevelFinished(dictGame)(v2);
                      return $74;
                  })());
              };
              return v1;
          };
      };
  };
  var _play$prime = function (dictGame) {
      return function (move) {
          return _play(dictGame)({
              move: move,
              pushToHistory: true
          });
      };
  };
  exports["canPlay"] = canPlay;
  exports["initialPosition"] = initialPosition;
  exports["isLevelFinished"] = isLevelFinished;
  exports["play"] = play;
  exports["Rules"] = Rules;
  exports["NoDialog"] = NoDialog;
  exports["ConfirmNewGame"] = ConfirmNewGame;
  exports["SoloMode"] = SoloMode;
  exports["DuelMode"] = DuelMode;
  exports["St"] = St;
  exports["Game"] = Game;
  exports["changeTurn"] = changeTurn;
  exports["undo"] = undo;
  exports["redo"] = redo;
  exports["reset"] = reset;
  exports["_play"] = _play;
  exports["_play'"] = _play$prime;
  exports["newGame"] = newGame;
  exports["newGame'"] = newGame$prime;
  exports["setDialog"] = setDialog;
  exports["confirmNewGame"] = confirmNewGame;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Game.Baseball.Model"] = $PS["Game.Baseball.Model"] || {};
  var exports = $PS["Game.Baseball.Model"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];
  var Control_Category = $PS["Control.Category"];
  var Data_Array = $PS["Data.Array"];
  var Data_Eq = $PS["Data.Eq"];
  var Data_EuclideanRing = $PS["Data.EuclideanRing"];
  var Data_Foldable = $PS["Data.Foldable"];
  var Data_HeytingAlgebra = $PS["Data.HeytingAlgebra"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Lib_Core = $PS["Lib.Core"];
  var Lib_Game = $PS["Lib.Game"];
  var Lib_Random = $PS["Lib.Random"];
  var example = new Lib_Game.St({
      position: [  ],
      nbBases: 5,
      history: [  ],
      redoHistory: [  ],
      dialog: Lib_Game.Rules.value,
      levelFinished: false,
      turn: 0,
      mode: Lib_Game.SoloMode.value
  });
  var baseballGame = new Lib_Game.Game(function (v) {
      return function (i) {
          return Data_Maybe.maybe(false)(function (x) {
              return Data_Foldable.elem(Data_Foldable.foldableArray)(Data_Eq.eqInt)(x)([ 1, v.value0.nbBases - 1 | 0, -1 | 0, 1 - v.value0.nbBases | 0 ]);
          })(Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array.index(v.value0.position)(0))(function (v1) {
              return Control_Bind.bind(Data_Maybe.bindMaybe)(Data_Array.index(v.value0.position)(i))(function (v2) {
                  return Control_Applicative.pure(Data_Maybe.applicativeMaybe)(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(v1)(2) - Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(v2)(2) | 0);
              });
          }));
      };
  }, function (v) {
      return Lib_Random.shuffle(Data_Array.range(0)((2 * v.value0.nbBases | 0) - 1 | 0));
  }, function (v) {
      return Data_Foldable.all(Data_Foldable.foldableArray)(Data_HeytingAlgebra.heytingAlgebraBoolean)(Control_Category.identity(Control_Category.categoryFn))(Data_Array.mapWithIndex(function (i) {
          return function (j) {
              return Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(i)(2) === Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(j)(2);
          };
      })(v.value0.position));
  }, function (v) {
      return function (i) {
          return Lib_Core.swap(0)(i)(v.value0.position);
      };
  });
  var setNbBases = (function () {
      var _setNbBases = function (i) {
          return function (v) {
              return new Lib_Game.St({
                  position: v.value0.position,
                  history: v.value0.history,
                  redoHistory: v.value0.redoHistory,
                  levelFinished: v.value0.levelFinished,
                  dialog: v.value0.dialog,
                  turn: v.value0.turn,
                  mode: v.value0.mode,
                  nbBases: i
              });
          };
      };
      return Lib_Game["newGame'"](baseballGame)(_setNbBases);
  })();
  exports["example"] = example;
  exports["setNbBases"] = setNbBases;
  exports["baseballGame"] = baseballGame;
})(PS);
(function(exports) {
  "use strict";            

  exports.cos = Math.cos;    

  exports.sin = Math.sin;      

  exports.pi = Math.PI;
})(PS["Math"] = PS["Math"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Math"] = $PS["Math"] || {};
  var exports = $PS["Math"];
  var $foreign = $PS["Math"];
  exports["cos"] = $foreign.cos;
  exports["sin"] = $foreign.sin;
  exports["pi"] = $foreign.pi;
})(PS);
(function(exports) {
  const RECYCLED_NODE = 1
  const LAZY_NODE = 2
  const TEXT_NODE = 3
  const EMPTY_OBJ = {}
  const EMPTY_ARR = []
  const map = EMPTY_ARR.map
  const isArray = Array.isArray
  const defer = requestAnimationFrame || setTimeout

  const merge = function(a, b) {
    var out = {}

    for (var k in a) out[k] = a[k]
    for (var k in b) out[k] = b[k]

    return out
  }

  const batch = list =>
    list.reduce((out, item) =>
      out.concat(
        !item || item === true
          ? 0
          : typeof item[0] === "function"
          ? [item]
          : batch(item)
      )
    , EMPTY_ARR)

  const isSameAction = (a, b) =>
    isArray(a) && isArray(b) && a[0] === b[0] && typeof a[0] === "function"

  const shouldRestart = function(a, b) {
    if (a !== b) {
      for (var k in merge(a, b)) {
        if (a[k] !== b[k] && !isSameAction(a[k], b[k])) return true
        b[k] = a[k]
      }
    }
  } 

  const patchSubs = function(oldSubs, newSubs, dispatch) {
    for (var
          i = 0, oldSub, newSub, subs = [];
      i < oldSubs.length || i < newSubs.length;
      i++
    ) {
      oldSub = oldSubs[i]
      newSub = newSubs[i]
      subs.push(
        newSub
          ? !oldSub ||
            newSub[0] !== oldSub[0] ||
            shouldRestart(newSub[1], oldSub[1])
            ? [
                newSub[0],
                newSub[1],
                newSub[0](dispatch, newSub[1]),
                oldSub && oldSub[2]()
              ]
            : oldSub
          : oldSub && oldSub[2]()
      )
    }
    return subs
  }

  const patchProperty = function(node, key, oldValue, newValue, listener, isSvg) {
    if (key === "key") {
    } else if (key === "style") {
      for (var k in merge(oldValue, newValue)) {
        oldValue = newValue == null || newValue[k] == null ? "" : newValue[k]
        if (k[0] === "-") {
          node[key].setProperty(k, oldValue)
        } else {
          node[key][k] = oldValue
        }
      }
    } else if (key[0] === "o" && key[1] === "n") {
      if (
        !((node.actions || (node.actions = {}))[
          (key = key.slice(2).toLowerCase())
        ] = newValue)
      ) {
        node.removeEventListener(key, listener)
      } else if (!oldValue) {
        node.addEventListener(key, listener)
      }
    } else if (!isSvg && key !== "list" && key in node) {
      node[key] = newValue == null ? "" : newValue
    } else if (
      newValue == null ||
      newValue === false ||
      (key === "class" && !newValue)
    ) {
      node.removeAttribute(key)
    } else {
      node.setAttribute(key, newValue)
    }
  }

  const createNode = function(vnode, listener, isSvg) {
    var node =
      vnode.type === TEXT_NODE
        ? document.createTextNode(vnode.name)
        : (isSvg = isSvg || vnode.name === "svg")
        ? document.createElementNS("http://www.w3.org/2000/svg", vnode.name)
        : document.createElement(vnode.name)
    var props = vnode.props

    for (var k in props) {
      patchProperty(node, k, null, props[k], listener, isSvg)
    }

    for (var i = 0, len = vnode.children.length; i < len; i++) {
      node.appendChild(
        createNode(
          (vnode.children[i] = getVNode(vnode.children[i])),
          listener,
          isSvg
        )
      )
    }

    return (vnode.node = node)
  }

  const getKey = function(vnode) {
    return vnode == null ? null : vnode.key
  }

  const patch = function(parent, node, oldVNode, newVNode, listener, isSvg) {
    if (oldVNode === newVNode) {
    } else if (
      oldVNode != null &&
      oldVNode.type === TEXT_NODE &&
      newVNode.type === TEXT_NODE
    ) {
      if (oldVNode.name !== newVNode.name) node.nodeValue = newVNode.name
    } else if (oldVNode == null || oldVNode.name !== newVNode.name) {
      node = parent.insertBefore(
        createNode((newVNode = getVNode(newVNode)), listener, isSvg),
        node
      )
      if (oldVNode != null) {
        parent.removeChild(oldVNode.node)
      }
    } else {
      var tmpVKid
      var oldVKid

      var oldKey
      var newKey

      var oldVProps = oldVNode.props
      var newVProps = newVNode.props

      var oldVKids = oldVNode.children
      var newVKids = newVNode.children

      var oldHead = 0
      var newHead = 0
      var oldTail = oldVKids.length - 1
      var newTail = newVKids.length - 1

      isSvg = isSvg || newVNode.name === "svg"

      for (var i in merge(oldVProps, newVProps)) {
        if (
          (i === "value" || i === "selected" || i === "checked"
            ? node[i]
            : oldVProps[i]) !== newVProps[i]
        ) {
          patchProperty(node, i, oldVProps[i], newVProps[i], listener, isSvg)
        }
      }

      while (newHead <= newTail && oldHead <= oldTail) {
        if (
          (oldKey = getKey(oldVKids[oldHead])) == null ||
          oldKey !== getKey(newVKids[newHead])
        ) {
          break
        }

        patch(
          node,
          oldVKids[oldHead].node,
          oldVKids[oldHead],
          (newVKids[newHead] = getVNode(
            newVKids[newHead++],
            oldVKids[oldHead++]
          )),
          listener,
          isSvg
        )
      }

      while (newHead <= newTail && oldHead <= oldTail) {
        if (
          (oldKey = getKey(oldVKids[oldTail])) == null ||
          oldKey !== getKey(newVKids[newTail])
        ) {
          break
        }

        patch(
          node,
          oldVKids[oldTail].node,
          oldVKids[oldTail],
          (newVKids[newTail] = getVNode(
            newVKids[newTail--],
            oldVKids[oldTail--]
          )),
          listener,
          isSvg
        )
      }

      if (oldHead > oldTail) {
        while (newHead <= newTail) {
          node.insertBefore(
            createNode(
              (newVKids[newHead] = getVNode(newVKids[newHead++])),
              listener,
              isSvg
            ),
            (oldVKid = oldVKids[oldHead]) && oldVKid.node
          )
        }
      } else if (newHead > newTail) {
        while (oldHead <= oldTail) {
          node.removeChild(oldVKids[oldHead++].node)
        }
      } else {
        for (var i = oldHead, keyed = {}, newKeyed = {}; i <= oldTail; i++) {
          if ((oldKey = oldVKids[i].key) != null) {
            keyed[oldKey] = oldVKids[i]
          }
        }

        while (newHead <= newTail) {
          oldKey = getKey((oldVKid = oldVKids[oldHead]))
          newKey = getKey(
            (newVKids[newHead] = getVNode(newVKids[newHead], oldVKid))
          )

          if (
            newKeyed[oldKey] ||
            (newKey != null && newKey === getKey(oldVKids[oldHead + 1]))
          ) {
            if (oldKey == null) {
              node.removeChild(oldVKid.node)
            }
            oldHead++
            continue
          }

          if (newKey == null || oldVNode.type === RECYCLED_NODE) {
            if (oldKey == null) {
              patch(
                node,
                oldVKid && oldVKid.node,
                oldVKid,
                newVKids[newHead],
                listener,
                isSvg
              )
              newHead++
            }
            oldHead++
          } else {
            if (oldKey === newKey) {
              patch(
                node,
                oldVKid.node,
                oldVKid,
                newVKids[newHead],
                listener,
                isSvg
              )
              newKeyed[newKey] = true
              oldHead++
            } else {
              if ((tmpVKid = keyed[newKey]) != null) {
                patch(
                  node,
                  node.insertBefore(tmpVKid.node, oldVKid && oldVKid.node),
                  tmpVKid,
                  newVKids[newHead],
                  listener,
                  isSvg
                )
                newKeyed[newKey] = true
              } else {
                patch(
                  node,
                  oldVKid && oldVKid.node,
                  null,
                  newVKids[newHead],
                  listener,
                  isSvg
                )
              }
            }
            newHead++
          }
        }

        while (oldHead <= oldTail) {
          if (getKey((oldVKid = oldVKids[oldHead++])) == null) {
            node.removeChild(oldVKid.node)
          }
        }

        for (var i in keyed) {
          if (newKeyed[i] == null) {
            node.removeChild(keyed[i].node)
          }
        }
      }
    }

    return (newVNode.node = node)
  }

  const propsChanged = function(a, b) {
    for (var k in a) if (a[k] !== b[k]) return true
    for (var k in b) if (a[k] !== b[k]) return true
  }

  const getVNode = function(newVNode, oldVNode) {
    return newVNode.type === LAZY_NODE
      ? ((!oldVNode || propsChanged(oldVNode.lazy, newVNode.lazy)) &&
          ((oldVNode = newVNode.lazy.view(newVNode.lazy)).lazy = newVNode.lazy),
        oldVNode)
      : newVNode
  }

  const createVNode = function(name, props, children, node, key, type) {
    return {
      name: name,
      props: props,
      children: children,
      node: node,
      type: type,
      key: key
    }
  }

  const createTextVNode = (value, node) =>
      createVNode(value, EMPTY_OBJ, EMPTY_ARR, node, null, TEXT_NODE);

  const recycleNode = node =>
    node.nodeType === TEXT_NODE
      ? createTextVNode(node.nodeValue, node)
      : createVNode(
          node.nodeName.toLowerCase(),
          EMPTY_OBJ,
          map.call(node.childNodes, recycleNode),
          node,
          null,
          RECYCLED_NODE
        )

  const Lazy = function(props) {
    return {
      lazy: props,
      type: LAZY_NODE
    }
  }

  const app = props => () => {
    let state = {}
    let lock = false
    const view = props.view;
    let node = document.getElementById(props.node);
    const subscriptions = props.subscriptions;
    let vdom = node && recycleNode(node)
    const subs = []

    const listener = function(event) {
      dispatch(this.actions[event.type], event)
    }

    const setState = newState => {
      if (state !== newState) {
        state = newState
        if (subscriptions) {
          subs = patchSubs(subs, batch([subscriptions(state)]), dispatch)
        }
        if (!lock) defer(render, (lock = true))
      }
      return state
    }

    const dispatch = action => {
      let res = action(state);
      //const fxs = res.fxs || [];
      //res = res.res;
      //batch(fxs.map(fx => fx && fx[0](dispatch, fx[1], props)));
      setState(res);
      return state;
    }


    const render = () => {
      lock = false
      node = patch(
        node.parentNode,
        node,
        vdom,
        vdom = view(state),
        listener
      )
    }

    dispatch(props.init)
  }

  const text = createTextVNode;

  const h = isStyle => name => ps => children => {
      const style = {};
      const props = {style: style};
      const vdom = { name: name, children: children.filter(x => x), props: props, node: null };
      const n = ps.length;
      for (let i = 0; i < n; i++) {
          const obj = ps[i];
          const value0 = obj.value0;
          const value1 = obj.value1;
          if (value1 === undefined)
              vdom.key = value0;
          else if (typeof value1 === 'function')
              vdom.props["on"+value0] = value1;
          else if (typeof value1 === 'boolean') {
              if(!value1)
                  {}
              else if (props.class)  
                  props.class += ' ' + value0;
              else
                  props.class = value0;
          }
          else if (isStyle(obj))
              style[value0] = value1;
          else
              props[value0] = value1;
      }
      return vdom;
  }

  exports.emptyNode = null;
  exports.app = app;
  exports.hAux = h;
  exports.text = text;
})(PS["Pha"] = PS["Pha"] || {});
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Pha"] = $PS["Pha"] || {};
  var exports = $PS["Pha"];
  var $foreign = $PS["Pha"];             
  var Key = (function () {
      function Key(value0) {
          this.value0 = value0;
      };
      Key.create = function (value0) {
          return new Key(value0);
      };
      return Key;
  })();
  var Attr = (function () {
      function Attr(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Attr.create = function (value0) {
          return function (value1) {
              return new Attr(value0, value1);
          };
      };
      return Attr;
  })();
  var Class = (function () {
      function Class(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Class.create = function (value0) {
          return function (value1) {
              return new Class(value0, value1);
          };
      };
      return Class;
  })();
  var Style = (function () {
      function Style(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Style.create = function (value0) {
          return function (value1) {
              return new Style(value0, value1);
          };
      };
      return Style;
  })();
  var Event = (function () {
      function Event(value0, value1) {
          this.value0 = value0;
          this.value1 = value1;
      };
      Event.create = function (value0) {
          return function (value1) {
              return new Event(value0, value1);
          };
      };
      return Event;
  })();
  var isStyle = function (v) {
      if (v instanceof Style) {
          return true;
      };
      return false;
  };
  var h = $foreign.hAux(isStyle);
  exports["Key"] = Key;
  exports["Attr"] = Attr;
  exports["Class"] = Class;
  exports["Style"] = Style;
  exports["Event"] = Event;
  exports["isStyle"] = isStyle;
  exports["h"] = h;
  exports["text"] = $foreign.text;
  exports["emptyNode"] = $foreign.emptyNode;
  exports["app"] = $foreign.app;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Pha.Html"] = $PS["Pha.Html"] || {};
  var exports = $PS["Pha.Html"];
  var Pha = $PS["Pha"];                
  var use = Pha.h("use");
  var svg = Pha.h("svg");
  var style = Pha.Style.create;
  var span = Pha.h("span");
  var rect = Pha.h("rect");
  var key = Pha.Key.create;
  var h2 = Pha.h("h2");
  var g = Pha.h("g");
  var div$prime = Pha.h("div");
  var click = Pha.Event.create("click");
  var class$prime = Pha.Class.create;
  var button = Pha.h("button");    
  var attr = Pha.Attr.create;
  var fill = attr("fill");
  var height = attr("height");
  var href = attr("href");
  var stroke = attr("stroke");
  var transform = attr("transform");
  var viewBox = attr("viewBox");
  var width = attr("width");
  var x = attr("x");
  var y = attr("y");
  exports["key"] = key;
  exports["attr"] = attr;
  exports["class'"] = class$prime;
  exports["style"] = style;
  exports["click"] = click;
  exports["button"] = button;
  exports["div'"] = div$prime;
  exports["span"] = span;
  exports["h2"] = h2;
  exports["width"] = width;
  exports["height"] = height;
  exports["href"] = href;
  exports["x"] = x;
  exports["y"] = y;
  exports["stroke"] = stroke;
  exports["fill"] = fill;
  exports["viewBox"] = viewBox;
  exports["transform"] = transform;
  exports["g"] = g;
  exports["svg"] = svg;
  exports["rect"] = rect;
  exports["use"] = use;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["UI.Dialog"] = $PS["UI.Dialog"] || {};
  var exports = $PS["UI.Dialog"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Pha = $PS["Pha"];
  var Pha_Html = $PS["Pha.Html"];                
  var dialog = function (v) {
      return function (children) {
          return Pha_Html["div'"]([ Pha_Html["class'"]("ui-absolute ui-flex-center ui-dialog-container")(true) ])([ Pha_Html["div'"]([ Pha_Html["class'"]("ui-dialog")(true) ])([ Pha_Html["div'"]([ Pha_Html["class'"]("ui-dialog-head")(true) ])([ Pha_Html["div'"]([ Pha_Html["class'"]("ui-dialog-title")(true) ])([ Pha.text(v.title) ]) ]), Pha_Html["div'"]([ Pha_Html["class'"]("ui-dialog-body")(true) ])(children), Pha_Html["div'"]([ Pha_Html["class'"]("ui-dialog-buttons")(true) ])([ Data_Maybe.maybe(Pha.emptyNode)(function (action) {
              return Pha_Html.button([ Pha_Html["class'"]("ui-button ui-button-primary")(true), Pha_Html.click(action) ])([ Pha.text("Annuler") ]);
          })(v.onCancel), Data_Maybe.maybe(Pha.emptyNode)(function (action) {
              return Pha_Html.button([ Pha_Html["class'"]("ui-button ui-button-primary")(true), Pha_Html.click(action) ])([ Pha.text("Ok") ]);
          })(v.onOk) ]) ]) ]);
      };
  };
  var card = function (title) {
      return function (children) {
          return Pha_Html["div'"]([ Pha_Html["class'"]("ui-card")(true) ])([ Pha_Html["div'"]([ Pha_Html["class'"]("ui-card-head ui-flex-center")(true) ])([ Pha_Html["div'"]([ Pha_Html["class'"]("ui-card-title")(true) ])([ Pha.text(title) ]) ]), Pha_Html["div'"]([ Pha_Html["class'"]("ui-card-body")(true) ])(children) ]);
      };
  };
  exports["card"] = card;
  exports["dialog"] = dialog;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["UI.Icon"] = $PS["UI.Icon"] || {};
  var exports = $PS["UI.Icon"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Semigroup = $PS["Data.Semigroup"];
  var Data_Show = $PS["Data.Show"];
  var Pha = $PS["Pha"];
  var Pha_Html = $PS["Pha.Html"];                
  var IconText = (function () {
      function IconText(value0) {
          this.value0 = value0;
      };
      IconText.create = function (value0) {
          return new IconText(value0);
      };
      return IconText;
  })();
  var IconSymbol = (function () {
      function IconSymbol(value0) {
          this.value0 = value0;
      };
      IconSymbol.create = function (value0) {
          return new IconSymbol(value0);
      };
      return IconSymbol;
  })();
  var IconNone = (function () {
      function IconNone() {

      };
      IconNone.value = new IconNone();
      return IconNone;
  })();
  var icongroup = function (title) {
      return function (children) {
          return Pha_Html["div'"]([  ])([ Pha_Html.h2([  ])([ Pha.text(title) ]), Pha_Html["div'"]([ Pha_Html["class'"]("ui-icon-grid")(true) ])(children) ]);
      };
  };
  var defaultOptions = {
      icon: IconNone.value,
      selected: false,
      tooltip: Data_Maybe.Nothing.value,
      round: false,
      large: false,
      hidden: false,
      disabled: false
  };
  var iconbutton = function (optionFn) {
      return function (props) {
          var v = optionFn(defaultOptions);
          return Pha_Html["div'"](Data_Semigroup.append(Data_Semigroup.semigroupArray)([ Pha_Html["class'"]("ui-icon")(true), Pha_Html["class'"]("selected")(v.selected), Pha_Html["class'"]("round")(v.large), Pha_Html["class'"]("hidden")(v.hidden), Pha_Html.attr("disabled")(Data_Show.show(Data_Show.showBoolean)(v.disabled)) ])(props))([ (function () {
              if (v.icon instanceof IconSymbol) {
                  return Pha_Html.svg([ Pha_Html.attr("width")("100%"), Pha_Html.attr("heigh")("100%"), Pha_Html["class'"]("ui-icon-symbol")(true) ])([ Pha_Html.use([ Pha_Html.attr("href")(v.icon.value0) ])([  ]) ]);
              };
              if (v.icon instanceof IconText) {
                  return Pha_Html.span([ Pha_Html["class'"]("ui-icon-text")(true) ])([ Pha.text(v.icon.value0) ]);
              };
              if (v.icon instanceof IconNone) {
                  return Pha.emptyNode;
              };
              throw new Error("Failed pattern match at UI.Icon (line 42, column 9 - line 50, column 26): " + [ v.icon.constructor.name ]);
          })(), Data_Maybe.maybe(Pha.emptyNode)(function (t) {
              return Pha_Html.span([ Pha_Html["class'"]("ui-icon-tooltip")(true) ])([ Pha.text(t) ]);
          })(v.tooltip) ]);
      };
  };
  exports["IconText"] = IconText;
  exports["IconSymbol"] = IconSymbol;
  exports["IconNone"] = IconNone;
  exports["defaultOptions"] = defaultOptions;
  exports["iconbutton"] = iconbutton;
  exports["icongroup"] = icongroup;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["UI.Icons"] = $PS["UI.Icons"] || {};
  var exports = $PS["UI.Icons"];
  var Data_Array = $PS["Data.Array"];
  var Lib_Game = $PS["Lib.Game"];
  var Pha = $PS["Pha"];
  var Pha_Html = $PS["Pha.Html"];
  var UI_Icon = $PS["UI.Icon"];                
  var winPanel = function (v) {
      return Pha_Html["div'"]([ Pha_Html["class'"]("ui-flex-center ui-absolute component-win-container")(true) ])([ Pha_Html["div'"]([ Pha_Html["class'"]("component-win")(true), Pha_Html["class'"]("visible")(v.value0.levelFinished) ])([ Pha.text("GAGN\xc9") ]) ]);
  };
  var iconbutton = function (dictGame) {
      return function (v) {
          return function (optionFn) {
              return function (props) {
                  return UI_Icon.iconbutton(optionFn)(props);
              };
          };
      };
  };
  var iredo = function (dictGame) {
      return function (action) {
          return function (v) {
              return iconbutton(dictGame)(new Lib_Game.St(v.value0))(function (v1) {
                  return {
                      icon: new UI_Icon.IconSymbol("#undo"),
                      selected: v1.selected,
                      tooltip: v1.tooltip,
                      round: v1.round,
                      large: v1.large,
                      hidden: v1.hidden,
                      disabled: Data_Array["null"](v.value0.history)
                  };
              })([ Pha_Html.click(action(Lib_Game.redo)) ]);
          };
      };
  };
  var ireset = function (dictGame) {
      return function (action) {
          return function (v) {
              return iconbutton(dictGame)(new Lib_Game.St(v.value0))(function (v1) {
                  return {
                      icon: new UI_Icon.IconSymbol("#reset"),
                      selected: v1.selected,
                      tooltip: v1.tooltip,
                      round: v1.round,
                      large: v1.large,
                      hidden: v1.hidden,
                      disabled: Data_Array["null"](v.value0.history)
                  };
              })([ Pha_Html.click(action(Lib_Game.reset)) ]);
          };
      };
  };
  var irules = function (dictGame) {
      return function (action) {
          return function (v) {
              var selected = (function () {
                  if (v.value0.dialog instanceof Lib_Game.Rules) {
                      return true;
                  };
                  return false;
              })();
              return iconbutton(dictGame)(new Lib_Game.St(v.value0))(function (v1) {
                  return {
                      icon: new UI_Icon.IconSymbol("#rules"),
                      selected: selected,
                      tooltip: v1.tooltip,
                      round: v1.round,
                      large: v1.large,
                      hidden: v1.hidden,
                      disabled: v1.disabled
                  };
              })([ Pha_Html.click(action(Lib_Game.setDialog(Lib_Game.Rules.value))) ]);
          };
      };
  };
  var iundo = function (dictGame) {
      return function (action) {
          return function (v) {
              return iconbutton(dictGame)(new Lib_Game.St(v.value0))(function (v1) {
                  return {
                      icon: new UI_Icon.IconSymbol("#undo"),
                      selected: v1.selected,
                      tooltip: v1.tooltip,
                      round: v1.round,
                      large: v1.large,
                      hidden: v1.hidden,
                      disabled: Data_Array["null"](v.value0.history)
                  };
              })([ Pha_Html.click(action(Lib_Game.undo)) ]);
          };
      };
  };
  exports["iconbutton"] = iconbutton;
  exports["iundo"] = iundo;
  exports["iredo"] = iredo;
  exports["ireset"] = ireset;
  exports["irules"] = irules;
  exports["winPanel"] = winPanel;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Game.Baseball.View"] = $PS["Game.Baseball.View"] || {};
  var exports = $PS["Game.Baseball.View"];
  var Data_Array = $PS["Data.Array"];
  var Data_EuclideanRing = $PS["Data.EuclideanRing"];
  var Data_Functor = $PS["Data.Functor"];
  var Data_Int = $PS["Data.Int"];
  var Data_Maybe = $PS["Data.Maybe"];
  var Data_Show = $PS["Data.Show"];
  var Game_Baseball_Model = $PS["Game.Baseball.Model"];
  var Lib_Core = $PS["Lib.Core"];
  var Lib_Game = $PS["Lib.Game"];
  var $$Math = $PS["Math"];
  var Pha = $PS["Pha"];
  var Pha_Html = $PS["Pha.Html"];
  var UI_Dialog = $PS["UI.Dialog"];
  var UI_Icon = $PS["UI.Icon"];
  var UI_Icons = $PS["UI.Icons"];                
  var translatePlayer = function (position) {
      return function (nbBases) {
          var mid = Data_Int.toNumber(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(position)(2));
          var x = 42.0 + 35.0 * $$Math.cos((mid * 2.0 * $$Math.pi) / Data_Int.toNumber(nbBases)) + Data_Int.toNumber(10 * Data_EuclideanRing.mod(Data_EuclideanRing.euclideanRingInt)(position)(2) | 0);
          var y = 46.0 + 35.0 * $$Math.sin((mid * 2.0 * $$Math.pi) / Data_Int.toNumber(nbBases));
          return "translate(" + (Data_Show.show(Data_Show.showNumber)(x) + ("%," + (Data_Show.show(Data_Show.showNumber)(y) + "%)")));
      };
  };
  var transformBase = function (i) {
      return function (nbBases) {
          var y = 500.0 + 350.0 * $$Math.sin((Data_Int.toNumber(i) * 2.0 * $$Math.pi) / Data_Int.toNumber(nbBases));
          var x = 500.0 + 350.0 * $$Math.cos((Data_Int.toNumber(i) * 2.0 * $$Math.pi) / Data_Int.toNumber(nbBases));
          return "translate(" + (Data_Show.show(Data_Show.showNumber)(x) + ("," + (Data_Show.show(Data_Show.showNumber)(y) + ") rotate(45)")));
      };
  };
  var colors = [ "blue", "red", "green", "magenta", "orange", "black", "cyan", "gray" ];
  var view = function (action) {
      return function (rndaction) {
          return function (v) {
              var levelFinished = Lib_Game.isLevelFinished(Game_Baseball_Model.baseballGame)(v);
              var dialog$prime = function (v1) {
                  if (v1 instanceof Lib_Game.Rules) {
                      return UI_Dialog.dialog({
                          title: "R\xe8gles",
                          onOk: new Data_Maybe.Just(action(Lib_Game.setDialog(Lib_Game.NoDialog.value))),
                          onCancel: Data_Maybe.Nothing.value
                      })([ Pha.text("blah blah blah blah") ]);
                  };
                  if (v1 instanceof Lib_Game.ConfirmNewGame) {
                      return UI_Dialog.dialog({
                          title: "R\xe8gles",
                          onCancel: new Data_Maybe.Just(action(Lib_Game.setDialog(Lib_Game.NoDialog.value))),
                          onOk: new Data_Maybe.Just(action(Lib_Game.confirmNewGame(v1.value0)))
                      })([ Pha.text("blah blah blah blah") ]);
                  };
                  return Pha.emptyNode;
              };
              var config = UI_Dialog.card("Baseball multicolore")([ UI_Icon.icongroup("nombres de bases")(Data_Functor.map(Data_Functor.functorArray)(function (i) {
                  return UI_Icons.iconbutton(Game_Baseball_Model.baseballGame)(v)(function (v1) {
                      return {
                          icon: UI_Icon.IconText.create(Data_Show.show(Data_Show.showInt)(i)),
                          selected: v.value0.nbBases === i,
                          tooltip: v1.tooltip,
                          round: v1.round,
                          large: v1.large,
                          hidden: v1.hidden,
                          disabled: v1.disabled
                      };
                  })([ Pha_Html.click(rndaction(Game_Baseball_Model.setNbBases(i))) ]);
              })([ 4, 5, 6, 7, 8 ])), UI_Icon.icongroup("Options")([ UI_Icons.iundo(Game_Baseball_Model.baseballGame)(action)(v), UI_Icons.iredo(Game_Baseball_Model.baseballGame)(action)(v), UI_Icons.ireset(Game_Baseball_Model.baseballGame)(action)(v), UI_Icons.irules(Game_Baseball_Model.baseballGame)(action)(v) ]) ]);
              var board = Pha_Html["div'"]([ Pha_Html["class'"]("ui-board baseball-board")(true) ])([ Pha_Html.svg([ Pha_Html.width("100%"), Pha_Html.height("100%"), Pha_Html.viewBox("0 0 1000 1000") ])(Data_Array.concat([ Lib_Core.repeat(v.value0.nbBases)(function (i) {
                  return Pha_Html.rect([ Pha_Html.key("b" + Data_Show.show(Data_Show.showInt)(i)), Pha_Html["class'"]("baseball-base")(true), Pha_Html.stroke(Data_Maybe.fromMaybe("black")(Data_Array.index(colors)(i))), Pha_Html.width("200"), Pha_Html.height("200"), Pha_Html.x("-100"), Pha_Html.y("-100"), Pha_Html.transform(transformBase(i)(v.value0.nbBases)) ])([  ]);
              }), Data_Array.mapWithIndex(function (player) {
                  return function (position) {
                      var $8 = player === 0;
                      if ($8) {
                          return Pha.emptyNode;
                      };
                      return Pha_Html.g([ Pha_Html["class'"]("baseball-player")(true), Pha_Html.style("transform")(translatePlayer(position)(v.value0.nbBases)), Pha_Html.key("p" + Data_Show.show(Data_Show.showInt)(player)) ])([ Pha_Html.use([ Pha_Html.href("#meeple"), Pha_Html.click(action(Lib_Game["_play'"](Game_Baseball_Model.baseballGame)(player))), Pha_Html.width("70"), Pha_Html.height("70"), Pha_Html.fill(Data_Maybe.fromMaybe("black")(Data_Array.index(colors)(Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(player)(2)))), Pha_Html.style("animation")((function () {
                          if (levelFinished) {
                              return "baseballHola 4s linear " + (Data_Show.show(Data_Show.showInt)(1000 + Data_EuclideanRing.div(Data_EuclideanRing.euclideanRingInt)(2000 * player | 0)(v.value0.nbBases) | 0) + "ms infinite");
                          };
                          return "none";
                      })()), Pha_Html.style("cursor")((function () {
                          var $10 = Lib_Game.canPlay(Game_Baseball_Model.baseballGame)(v)(player);
                          if ($10) {
                              return "pointer";
                          };
                          return "not-allowed";
                      })()) ])([  ]) ]);
                  };
              })(v.value0.position) ])) ]);
              return Pha_Html["div'"]([  ])([ Pha_Html["div'"]([ Pha_Html["class'"]("main-container")(true) ])([ Pha_Html["div'"]([  ])([ board, UI_Icons.winPanel(v) ]), config ]), dialog$prime(v.value0.dialog) ]);
          };
      };
  };
  exports["colors"] = colors;
  exports["translatePlayer"] = translatePlayer;
  exports["transformBase"] = transformBase;
  exports["view"] = view;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Optic.Lens"] = $PS["Optic.Lens"] || {};
  var exports = $PS["Optic.Lens"];
  var Data_Functor = $PS["Data.Functor"];                
  var lens = function (s2a) {
      return function (s2b2t) {
          return function (dictFunctor) {
              return function (a2fb) {
                  return function (s) {
                      return Data_Functor.map(dictFunctor)(s2b2t(s))(a2fb(s2a(s)));
                  };
              };
          };
      };
  };
  exports["lens"] = lens;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.2
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Control_Applicative = $PS["Control.Applicative"];
  var Control_Bind = $PS["Control.Bind"];
  var Data_Const = $PS["Data.Const"];
  var Data_Identity = $PS["Data.Identity"];
  var Data_Profunctor = $PS["Data.Profunctor"];
  var Game_Baseball_Model = $PS["Game.Baseball.Model"];
  var Game_Baseball_View = $PS["Game.Baseball.View"];
  var Lib_Random = $PS["Lib.Random"];
  var Optic_Getter = $PS["Optic.Getter"];
  var Optic_Lens = $PS["Optic.Lens"];
  var Optic_Setter = $PS["Optic.Setter"];
  var Pha = $PS["Pha"];                
  var root = {
      baseball: Game_Baseball_Model.example,
      seed: 90192011
  };
  var rndlens = function (dictFunctor) {
      return Optic_Lens.lens(function (r) {
          return r.seed;
      })(function (r) {
          return function (x) {
              return {
                  seed: x,
                  baseball: r.baseball
              };
          };
      })(dictFunctor);
  };
  var mylens = function (dictFunctor) {
      return Optic_Lens.lens(function (r) {
          return r.baseball;
      })(function (r) {
          return function (x) {
              return {
                  baseball: x,
                  seed: r.seed
              };
          };
      })(dictFunctor);
  };
  var rndaction = function (f) {
      return function (st) {
          return Lib_Random.run(function (dictFunctor) {
              return rndlens(dictFunctor);
          })(st)(Control_Bind.bind(Lib_Random.bindRandom)(f(Optic_Getter.weiv(st)(mylens(Data_Const.functorConst))))(function (v) {
              return Control_Applicative.pure(Lib_Random.applicativeRandom)(Optic_Setter.set(mylens(Data_Identity.functorIdentity))(v)(st));
          }));
      };
  };
  var laction = Optic_Setter.over(Data_Profunctor.profunctorFn)(mylens(Data_Identity.functorIdentity));
  var main = Pha.app({
      init: function (x) {
          return root;
      },
      view: function (st) {
          return Game_Baseball_View.view(laction)(rndaction)(st.baseball);
      },
      node: "root"
  });
  exports["root"] = root;
  exports["mylens"] = mylens;
  exports["rndlens"] = rndlens;
  exports["laction"] = laction;
  exports["rndaction"] = rndaction;
  exports["main"] = main;
})(PS);
PS["Main"].main();